apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - backend.yaml
  - frontend.yaml
  - migrate-job.yaml

images:
  - name: gym-tracker-backend
    newName: us-central1-docker.pkg.dev/terraform-498709/gym-tracker/gym-tracker-backend
    newTag: latest
  - name: gym-tracker-frontend
    newName: us-central1-docker.pkg.dev/terraform-498709/gym-tracker/gym-tracker-frontend
    newTag: latest
